Repository eukarya-inc/PLATEAU-VIEW, pull requests merged in 2025-01, with the labels that each got.

#385 ci: migrate Visualizer frontend workflow to Cloud Run
  .github/workflows/deploy-reearth-visualizer-dev.yml
Labels: ci

#377 feat(server): resolve code space value on CityGML attributes API
  server/citygml/attributes.go
  server/citygml/attributes_test.go
  server/citygml/echo.go
  server/citygml/testdata/codelists/BuildingDataQualityAttribute_lod1HeightType.xml
  server/citygml/testdata/codelists/BuildingDataQualityAttribute_srcScale.xml
  server/citygml/testdata/codelists/Common_localPublicAuthorities.xml
  server/citygml/testdata/codelists/Common_urbanPlanType.xml
  server/citygml/testdata/codelists/LandSlideRiskAttribute_areaType.xml
  server/citygml/testdata/codelists/LandSlideRiskAttribute_description.xml
  server/citygml/testdata/udx/bldg/52382287_bldg_6697_psc_op.gml
Labels: server

#381 feat(server): CityGML features API
  server/citygml/attributes.go
  server/citygml/echo.go
  server/citygml/features.go
  server/citygml/features_test.go
  server/datacatalog/repos.go
  server/geo/geo.go
  server/go.mod
  server/go.sum
  server/spatialid/spatialid.go
Labels: server

#388 feat(server): CityGML SpatialID Attributes API
  server/citygml/attributes.go
  server/citygml/echo.go
  server/citygml/features.go
  server/citygml/processor.go
  server/citygml/spatialid_attributes.go
  server/citygml/spatialid_attributes_test.go
  server/config.go
  server/datacatalog/bounds.go
  server/datacatalog/repos.go
  server/geo/geo.go
  server/geo/jisx0410/jisx0410.go
  server/geo/spatialid/spatialid.go
  server/go.mod
Labels: server

#389 feat(server): add mm conditions to Datacatalog CityGML Files API
  server/citygml/echo.go
  server/datacatalog/repos.go
  server/geo/jisx0410/jisx0410.go
Labels: server

#390 perf(server): improve CityGML SpatialID Attributes API performance
  server/citygml/attributes.go
  server/citygml/echo.go
  server/citygml/processor.go
  server/citygml/spatialid_attributes.go
  server/citygml/spatialid_attributes_test.go
Labels: server

#391 perf(server): use etag to skip the same gml
  go.work.sum
  server/citygml/echo.go
  server/citygml/spatialid_attributes.go
Labels: server

#393 perf(server): improve CityGML SpatialID Attributes API performance
  server/citygml/attributes.go
  server/citygml/attributes_test.go
  server/citygml/features.go
  server/citygml/processor.go
  server/citygml/spatialid_attributes.go
  server/citygml/spatialid_attributes_test.go
Labels: server

#394 ci: add Visualizer Web deploy for prod
  .github/workflows/deploy-reearth-visualizer-prod.yml
Labels: ci

#395 ci: add Re:Earth Classic web deploy job
  .github/workflows/deploy-reearth-classic-dev.yml
  .github/workflows/deploy-reearth-classic-prod.yml
Labels: ci

#396 ci: fix image name for Classic Web in dev job
  .github/workflows/deploy-reearth-classic-dev.yml
Labels: ci

#402 ci: add flow workflow support
  .github/workflows/deploy-reearth-flow-dev.yml
  .github/workflows/deploy-reearth-flow-prod.yml
Labels: ci

#404 ci: remove no need push in Classic Web
  .github/workflows/deploy-reearth-classic-prod.yml
Labels: ci

#407 ci: remove GCS upload job and unnecessary `gcloud` setup
  .github/workflows/deploy-cms-dev.yml
  .github/workflows/deploy-cms-prod.yml
  .github/workflows/deploy-extension-dev.yml
  .github/workflows/deploy-extension-prod.yml
  .github/workflows/deploy-geo-dev.yml
  .github/workflows/deploy-geo-prod.yml
  .github/workflows/deploy-reearth-classic-dev.yml
  .github/workflows/deploy-reearth-classic-prod.yml
  .github/workflows/deploy-reearth-flow-dev.yml
  .github/workflows/deploy-reearth-flow-prod.yml
  .github/workflows/deploy-reearth-visualizer-dev.yml
  .github/workflows/deploy-reearth-visualizer-prod.yml
  .github/workflows/deploy-server-dev.yml
  .github/workflows/deploy-server-prod.yml
  .github/workflows/deploy-tiles-dev.yml
  .github/workflows/deploy-tiles-prod.yml
  .github/workflows/deploy-worker-dev.yml
  .github/workflows/deploy-worker-prod.yml
Labels: ci

#411 ci: remove unnecessary `setup-gcloud`
  .github/workflows/deploy-cms-prod.yml
  .github/workflows/deploy-geo-dev.yml
  .github/workflows/deploy-server-dev.yml
  .github/workflows/deploy-server-prod.yml
Labels: ci

#414 ci: add missing `setup-gcloud` for GCS using workflow
  .github/workflows/deploy-extension-dev.yml
  .github/workflows/deploy-extension-prod.yml
Labels: ci

#415 chore: Merge main into dev
  .github/workflows/deploy-extension-dev.yml
  .github/workflows/deploy-extension-prod.yml
Labels: ci, server
